"use client";

import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <title>Weather App</title>
      <meta name="description" content="Generated by create next app" />
      <body>
        <Main />

        <NextScript />
      </body>
    </Html>
  );
}
